export const PATHS = {
  github: 'https://github.com/h-jennings',
  twitter: 'https://twitter.com/jennings_hunter',
  linkedin: 'https://www.linkedin.com/in/hunter-jennings-591877b0/',
  seagulls: 'https://www.elegantseagulls.com/',
  email: 'mailto:jenningsdhunter@gmail.com',
  base: 'https://www.hunterjennings.dev',
  home: '/',
  about: '/about',
  writing: '/writing',
  work: '/work',
  dwr: '/work/dwr',
  nfip: '/work/nfip',
  portfolioV2: '/work/portfolio-v2',
  portfolioV2Url: 'https://v2.hunterjennings.dev',
} as const;
