export const PATHS = {
  github: 'https://github.com/h-jennings',
  twitter: 'https://twitter.com/jennings_hunter',
  linkedin: 'https://www.linkedin.com/in/hunter-jennings-591877b0/',
  seagulls: 'https://www.elegantseagulls.com/',
  email: 'mailto:jenningsdhunter@gmail.com',
  base: process.env.NEXT_PUBLIC_URL,
  home: '/',
  about: '/about',
  writing: '/writing',
  now: '/now',
  work: '/work',
  dwr: '/work/dwr',
  nfip: '/work/nfip',
  'audible-quiz': '/work/audible-quiz',
  audibleQuizUrl:
    'https://www.audible.com/quiz/audible-beat-the-sunday-scaries-escape-the-room',
  portfolioV2: '/work/portfolio-v2',
  portfolioV2Url: 'https://v2.hunterjennings.dev',
  writings: './src/data/writings',
  data: './src/data/',
} as const;
